const actionTypes = {
   LOGIN_SUCCESS: "LOGIN_SUCCESS",
   LOGIN_FAIL: "LOGIN_FAIL",
   REGISTER_SUCCESS: "REGISTER_SUCCESS",
   REGISTER_FAIL: "REGISTER_FAIL",
   LOGOUT: "LOGOUT",

   GET_POSTS: "GET_POSTS",
   GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
   GET_POSTS_MANAGER: "GET_POSTS_MANAGER",
   GET_NEW_POSTS: "GET_NEW_POSTS",
   EDIT_DATA: "EDIT_DATA",
   RESET_DATA_EDIT: "RESET_DATA_EDIT",

   GET_CATEGORIES: "GET_CATEGORIES",
   GET_PRICES: "GET_PRICES",
   GET_ACREAGE: "GET_ACREAGE",
   GET_PROVINCE: "GET_PROVINCE",

   GET_CURRENT: "GET_CURRENT",
};

export default actionTypes;
